# Generated by Django 6.1.1 on 2026-09-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('show_time', models.CharField(max_length=20)),
                ('ticket_price', models.IntegerField()),
                ('available_seats', models.IntegerField(default=50)),
            ],
        ),
    ]
